version: "3"
services:
  web:
    image: httpd
    ports:
      - "80:80"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    build:  ./
    volumes:
    - ./fluentd/conf/fluentd.conf:/fluentd/etc/fluent.conf
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "5140:5140"
      - "5140:5140/udp"


  elasticsearch:
    image: elasticsearch:7.13.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.13.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
