{
 "title": "Prometheus - AD and DNS",
 "description": "Active Directory and DNS Dashboard using Prometheus windows_Exporter ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(windows_dns_queries_total{protocol=\"udp\"}[1m]))"
    }
   ]
  },
  {
   "title": "DNS Queries/Sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(windows_dns_queries_total{protocol=\"udp\"}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Connections/Sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Searches",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(windows_ad_ldap_searches_total{}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Searches / Sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(windows_ad_ldap_searches_total{}[1m]))"
    }
   ]
  },
  {
   "title": "DNS Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS Queries/Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_dns_queries_total{}[1m])",
     "legendFormat": "in-{{protocol}} ({{instance}})"
    },
    {
     "expr": "-delta(windows_dns_responses_total{}[1m])",
     "legendFormat": "out-{{protocol}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Recursive Queries / Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_dns_recursive_query_failures_total[1m])",
     "legendFormat": "failures ({{instance}})"
    },
    {
     "expr": "delta(windows_dns_recursive_queries_total[1m])",
     "legendFormat": "queries ({{instance}})"
    },
    {
     "expr": "delta(windows_dns_recursive_query_send_timeouts_total[1m])",
     "legendFormat": "sent timeouts ({{instance}})"
    }
   ]
  },
  {
   "title": "AD Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pending Syncronisations",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(windows_ad_replication_pending_synchronizations{})"
      }
     ]
    },
    {
     "title": "Pending Operations",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(windows_ad_replication_pending_operations{})"
      }
     ]
    },
    {
     "title": "Inbound Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_replication_inbound_objects_updated_total{}[1m])",
       "legendFormat": "objects ({{instance}})"
      },
      {
       "expr": "delta(windows_ad_replication_inbound_properties_updated_total{}[1m])",
       "legendFormat": "properties ({{instance}})"
      }
     ]
    },
    {
     "title": "Intrasite Replication Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_replication_data_intrasite_bytes_total{direction=\"inbound\"}[1m])",
       "legendFormat": "inbound ({{instance}})"
      },
      {
       "expr": "-delta(windows_ad_replication_data_intrasite_bytes_total{direction=\"outbound\"}[1m])",
       "legendFormat": "outbound ({{instance}})"
      }
     ]
    },
    {
     "title": "Intersite Replication Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_replication_data_intersite_bytes_total{direction=\"inbound\"}[1m])",
       "legendFormat": "inbound ({{instance}})"
      },
      {
       "expr": "-delta(windows_ad_replication_data_intersite_bytes_total{direction=\"inbound\"}[1m])",
       "legendFormat": "outbound ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "AD Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "AD Operations (Detailed)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_directory_operations_total{}[1m])",
       "legendFormat": "{{origin}}-{{operation}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Directory Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_database_operations_total{}[1m])",
       "legendFormat": "{{operation}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "AD Binds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "AD Bind",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_binds_total{}[1m])",
       "legendFormat": "{{bind_method}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "AD LDAP Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "LDAP Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[1m])",
       "legendFormat": "Opened ({{instance}})"
      },
      {
       "expr": "-(delta(windows_ad_ldap_closed_connections_total{}[1m]))",
       "legendFormat": "Closed ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "AD Heatmap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "LDAP connections HeatMap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[1m])"
      }
     ]
    },
    {
     "title": "LDAP Searches",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "delta(windows_ad_ldap_searches_total{instance=\"ds-dc3:9182\"}[1m])"
      }
     ]
    }
   ]
  },
  {
   "title": "AD LDAP Searches/Updates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "LDAP Searches/Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_ldap_writes_total{}[1m])",
       "legendFormat": "Writes ({{instance}})"
      },
      {
       "expr": "-delta(windows_ad_ldap_searches_total{}[1m])",
       "legendFormat": "Searches ({{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DNS Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(windows_dns_memory_used_bytes_total{}[5m])",
       "legendFormat": "{{area}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Updates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_dns_dynamic_updates_received_total[1m])",
       "legendFormat": "{{operation}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_dns_dynamic_updates_failures_total[1m])",
       "legendFormat": "{{reason}} ({{instance}})"
      }
     ]
    }
   ]
  }
 ]
}